name: build
on:
  push:
    branches:
    - master
    - 'release-*'
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.16.15
    - uses: actions/checkout@v2
    - name: Run build
      run: go build -o haproxy-ingress pkg/main.go
    - name: Run tests
      run: go test ./...
